---
driver:
  name: terraform
  command_timeout: 1800

provisioner:
  name: terraform

verifier:
  name: terraform
  color: true
  fail_fast: true

suites:
  - name: kt_suite
    driver:
      root_module_directory: test/fixtures/tf_module
    verifier:
      systems:
        - name: inspec-gcp
          backend: gcp
          controls:
            - instance
  - name: node_standard
    driver:
      root_module_directory: test/fixtures/tf_module
    verifier:
      systems:
        - name: inspec-gcp
          backend: gcp
          controls:
            - node_standard

platforms:
  - name: terraform
